Q1. Create a function to check whether numpy array has Zero values or not.

In [30]:
import numpy as np
def check(a):
    if 0 in a:
        print("0 present in array")
    else:
        print("0 not in array")
        
a=np.random.randint(low=0,high=200,size=10)
print("array generated is")
print(a)
check(a)


array generated is
[ 64 185   0  22 193 117   6 151  92 106]
0 present in array


Q2.Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [53]:
import numpy as np    
a=np.random.randint(low=5,high=100,size=20)
print("original list of marks is",a)
c=0
for x in a:
        if x<40:
            a=np.delete(a,c)
        else:
            c=c+1
print("list of passing marks",a)
median=np.median(a)
mean=np.mean(a)
print("median of marks of students with passing marks",median)
print("mean of marks of students with passing marks",mean)


original list of marks is [19 23 82 28 98 28 65 19 62 83 86  8 81  9 32 44 38 50 22 20]
list of passing marks [82 98 65 62 83 86 81 44 38 50]
median of marks of students with passing marks 73.0
mean of marks of students with passing marks 68.9


Q3.Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [90]:
import numpy as np    
labels={'18':'First','19':'Second','20':'Third','21':'Fourth'}    
dob=np.array(['1998-02-04','1999-04-03','1997-05-02','2001-02-01','2000-03-04'],dtype='datetime64')
today=np.datetime64('2019-02-11')
diff=[]
for i in range(len(dob)):
    diff.append(str((today-dob[i])/365).replace(' days',''))
    
d=np.array(diff)
print("ages obtained are",d)
for index,i in enumerate(d):
    if i in labels:
        print(dob[index],labels[i])



ages obtained are ['21' '19' '21' '18' '18']
1998-02-04 Fourth
1999-04-03 Second
1997-05-02 Fourth
2001-02-01 First
2000-03-04 First


Q4.Create a function to sort 2d Array by a column.

In [12]:
import numpy as np

def sort_col(c,a):
    #for all rows and column c : [a[:,c].argsort()] we get a list of of index of rows in sorted order
    a = a[a[:,c].argsort()] 
    return a
    
a=np.array([['sarah','17','80'],['neha','20','65'],['priya','15','90'],['akanksha','21','75']])
c=int(input("enter column to sort"))
print("original matrix")
print(a)
print("after sort")
print(sort_col(c,a))
    
    

enter column to sort1
original matrix
[['sarah' '17' '80']
 ['neha' '20' '65']
 ['priya' '15' '90']
 ['akanksha' '21' '75']]
after sort
[['priya' '15' '90']
 ['sarah' '17' '80']
 ['neha' '20' '65']
 ['akanksha' '21' '75']]


Q5.Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be

   array([[ 0.,  1.,  0.],

             [ 0.,  0.,  1.],

             [ 0.,  1.,  0.],

             [ 0.,  1.,  0.],

             [ 0.,  1.,  0.],

            [ 1.,  0.,  0.]])

In [76]:
import numpy as np
a=np.random.randint(low=1,high=4,size=4)
l=[]
print(a)
for index,i in enumerate(a):
        b = np.zeros(4)
        b[i-1]=1
        l.append(list(b))
print("one hot encoding is as follow")
c=np.array(l)
print(c)

[3 3 3 2]
one hot encoding is as follow
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


Q6.Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [45]:
import numpy as np
a=np.array([1,2,3,np.nan,5,6,7,np.nan])
c=0
for i in a:
    if np.isnan(i)==True:
        a=np.delete(a,c)
    else:
        c=c+1
b=np.array(a,dtype='int')        
print(b)

[1 2 3 5 6 7]


Q7.Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [77]:
import numpy as np    
maxima=[]
a=np.random.randint(low=0,high=20,size=10)
print(a)
for index,i in enumerate(a):
    if index==0:
        if a[index]>a[index+1]:
            maxima.append(index)
   
    elif index!=len(a)-1 and index!=0:
            if a[index]>a[index+1] and a[index-1]<a[index]:
                  maxima.append(index)
    
    elif index==len(a)-1:
          if a[index-1]<a[index]:
                 maxima.append(index)

b=np.array(maxima)
print("array of local maximas is",b)



[ 5 13  8 16 14 12  5 19  6 19]
array of local maximas is [1 3 7 9]


Q8.From a given 1d array arr, generate a 2d matrix using strides,

For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

w and s will be provided by user.

In [79]:
import numpy as np
a=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
w=int(input('Enter window size'))
s=int(input('Enter stride size'))
p=0
win=0
l=[]
while p<len(a)-s:
    win=p+w
    l.append(list(a[p:win]))
    p=p+s

print(l)

Enter window size4
Enter stride size2
[[0, 1, 2, 3], [2, 3, 4, 5], [4, 5, 6, 7], [6, 7, 8, 9], [8, 9, 10, 11], [10, 11, 12, 13], [12, 13, 14]]
